sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "udemy-docker-and-k8s-frontend"
  env: "UdemyDockerAndK8sFrontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-130318069880"
  bucket_path: "udemy-docker-and-k8s-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
